services:
  spring-boot-app:
    image: anasortukov/audio-book
    ports:
      - "80:8080"
    depends_on:
      - postgres-db

  postgres-db:
    image: anasortukov/postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    ports:
      - "5433:5432"

  redis-db:
    image: redis
    ports:
      - "6300:6379"