spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audio_book
#    url: jdbc:postgresql://postgres_db:5432/postgres
    username: postgres
    password: root123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 240988a18d1f79
    password: 049160faae58ab
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 20MB