
spring:

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 100MB
  data:
    redis:
      host: localhost
      port: 6379

keys:
  jwt: ${JWT_SECRET_KEY}
  aws:
    access: ${AWS_S3_ACCESS_KEY}
    secret: ${AWS_S3_SECRET_KEY}
  bucket-name: ${AWS_S3_BUCKET_NAME}

logging:
  level:
    root: warn
server:
  port: 80
